### ISSUE TITLE
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.7/site-packages/itsdangerous/init.py)

### ISSUE THREAD

**Issue by masafumiohta** [masafumiohta/docker-kvs#3]
当該書籍について、そのまま実行すると、
docker run -it docker_kvs_app /bin/bash
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from flask import Flask, jsonify, request
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.7/site-packages/itsdangerous/__init__.py)
とでて、itsdangerousがないことで怒られて全体的に起動しない。
よって、
RUN pip install flask==1.1.4 redis==3.3.8 itsdangerous==1.1.0  markupsafe==2.0.1を/app/Dockerfileに追記して、起動させた。経緯は不明だが、書籍自体がこのあたりのアップデートをしていないことによるものと思われる。

**Comment by masafumiohta** [comment]
Change Subject
